### PR TITLE
Implemented C_SetPIN

### PR DESCRIPTION
**Pull request by denisenkom**

### CODE REVIEW

**Comment by a-dma** [comment]
Hey, thanks for the contribution.

This function has not been implemented so far because it's not clear how to map a PKCS#11 PIN to a PIV PIN/mgm key.

The way I see it there are two alternatives:

Leaving the PUK unmapped (and relying on yubico-piv-tool for that)
PKCS#11 | PIV
--- | ---
User | PIN
 | PUK
SO | Mgm Key

Allowing to call C_SetPin while not logged in
PKCS#11 | PIV
--- | ---
Not logged | PIN
User | PUK
SO | Mgm Key

Between these two I prefer the former.

Also, some checks fail on Travis. You want to export the new functions in ykpiv.map.

The rest looks good to me.

@klali Please let me know if you have comments on the libykpiv side of things (if we merge this we should also bump the libtool versions). Obviously you're also welcome to have an opinion on the PIN discussion.

**Comment by denisenkom** [comment]
I think the correct way to handle this is this:
```
PKCS#11       | PIV
------------- | ---
Not logged in | PIN
User          | PIN
SO            | Mgm Key
```

That fits better with standard, here is quote:

> C_SetPIN modifies the PIN of the user that is currently logged in, or the CKU_USER PIN if the session is not logged in.

As for exporting functions in ykpiv.map: What version should I specify, 1.2.0? e.g.:
```
YKPIV_1.2.0
{
global:
	ykpiv_change_pin;
	ykpiv_change_puk;
    ykpiv_unblock_pin;
} YKPIV_1.1.0;
```

**Comment by a-dma** [comment]
At this stage I'm fine with most solutions.
I think the one you proposed is as good as any. We can always change it later if there are problems.

The version would be 1.2.1

**Comment by denisenkom** [comment]
updated

**Comment by a-dma** [comment]
Merging, thanks a lot.

**Pull request merged**
