### PR TITLE
Add touch and PIN policy support to YKCS11

### PR DESCRIPTION
**Pull request by kevinjacobs**
Add touch and PIN policy support to YKCS11. Addresses https://github.com/Yubico/yubico-piv-tool/issues/341

A couple of notes:

- The single `CKA_VENDOR_DEFINED` attribute may not be ideal, but I've largely followed the prior art (i.e. the previous implementation and the defines still present in pkcs11y.h) while adding query policy support through `C_GetAttributeValue`.
- The value of `CKA_TOUCH_NEVER` is changed from 0x16 (22) to 16. I believe the 0x16 definition was a mistake, given that the others are single-bit values.
- Policy attributes are only supported via `C_GenerateKeyPair` and not with key import.
- I only have a YubiKey 5 NFC FIPS for testing. I attempted to account for Neo slots in `ykcs11_tests.c`, but it would be good to run the tests on any other available devices.

Happy to make adjustments as needed.

### CODE REVIEW

**Comment by qpernil** [comment]
Thanks for your pull request, we will evaluate your code after the holidays!

**Comment by qpernil** [comment]
I understand the sentiment of keeping it as it was, but it's unfortunate to call these values CKA_something, when the CKA prefix typically means an attribute id, such as CKA_ALWAYS_AUTHENTICATE. I also don't think it makes sense to have the different values represented as flags when it clearly wouldn't make sense to specify more than one. As written it is now implementation dependent which flag takes precedence in such cases. Again, I realize if this is to keep it compatible, so this is not a critique. But I think we need to change. We also shouldn't use the generic attribute ID CKA_VENDOR_DEFINED directly, instead adopting the technique demostrated in pkcs11y.h in the yubihsm-shell project. And as I mentioned in the original issue, we should probably also support CKA_ALWAYS_AUTHENTICATE for pin policy.

**Comment by kevinjacobs** [comment]
> I understand the sentiment of keeping it as it was, but it's unfortunate to call these values CKA_something, when the CKA prefix typically means an attribute id, such as CKA_ALWAYS_AUTHENTICATE. I also don't think it makes sense to have the different values represented as flags when it clearly wouldn't make sense to specify more than one. As written it is now implementation dependent which flag takes precedence in such cases. Again, I realize if this is to keep it compatible, so this is not a critique. But I think we need to change. We also shouldn't use the generic attribute ID CKA_VENDOR_DEFINED directly, instead adopting the technique demostrated in pkcs11y.h in the yubihsm-shell project. And as I mentioned in the original issue, we should probably also support CKA_ALWAYS_AUTHENTICATE for pin policy.

Maybe I should have been more clear when asking what would need to change from the previous implementation (my initial patch did exactly what you suggest :)). 

Thanks for the yubihsm-shell pointer - I wasn't sure what magic value would be needed to offset from CKA_VENDOR_DEFINED.

I'll re-work the interface accordingly. At this point I can't promise that I'll have bandwidth for the import case, but I'll see what I can do.

**Comment by kevinjacobs** [comment]
Comments addressed. I'm willing to add similar functionality to the key import path, but I'd prefer to do that in another PR.

**Comment by qpernil** [comment]
Hi again, and thx for the pull request. It looks good except for a couple of minor points:
First, I think in general setting values to the same they already are should be allowed (including setting them to the default), hence I don't see why the booleans couldn't be set to false, which you currently disallow.
The second point is sort of the same as the one I made before, it is still possible to set conflicting values since the pin- and touch policy can each just have one value (I know you check for that, this is just in principle). I think it would make more sense to have just two attributes, each with the appropriate values also defined. I suggest just echoing the values from ykpiv.h for the policies. Also, such values should not be prefixed CKA, which implies they define an attribute type, not a value. I think the code will even be simplified by such a change.
Best regards!

**Comment by qpernil** [comment]
One more thing - I'm going to create a PR to consistently set the length field of attributes we fail to fetch to CK_UNAVAILABLE_INFORMATION, it would be good if you could rebase on top of that and make sure you do that for your attributes too. Thx. It's not 100% clear in the pkcs#11 spec that this should be done, but it makes a lot of sense to do so I think. And we do that in yubihsm_pkcs11.

**Comment by qpernil** [comment]
Coming back to the above about CK_UNAVAILABLE_INFORMATION - you won't need to to that as https://github.com/Yubico/yubico-piv-tool/pull/353 now sets that externally to the get_attribute functions. Hence it has been removed where it was being set before.

**Comment by qpernil** [comment]
The last issue that will have to be addressed is that get_metadata will fail on most older YubiKeys, it is only from version 5.3 that it is supported. For the proprietary attributes I think this is fine, but for CKA_ALWAYS_AUTHENTICATE we probably need to fall back to the table-driven approach if metadata fails. We could also try attestation if metadata fails. Or maybe first, as the library will have created and saved attestations automatically. The metadata is encoded as X.509 certificate extensions, documented here https://developers.yubico.com/PIV/Introduction/PIV_attestation.html.

**Comment by kevinjacobs** [comment]
Thanks for the review, it's indeed simpler to implement and use this way.

I opted for just checking if get_metadata fails with `YKPIV_NOT_SUPPORTED`, then fall back to the table. The tests are a bit slow, but I wanted to make sure all slots behave as expected. Switching some of those to import (rather than GenerateKeyPair) in the follow-on will improve that.

**Comment by qpernil** [comment]
Hi, I have one final comment on the PR, and I think you might have meant this before and I missed that. For the CKA_ALWAYS_AUTHENTICATE I think to leave it out OR to pass a FALSE should mean the same thing, i.e. default PIN policy for that key. This is more in line with PKCS#11 in that specifying the default value for an attribute is exactly the same as not specifying it. Also, I think the test for CKA_ALWAYS_AUTHENTICATE should follow the pattern of the other two attributes, i.e. failing only if trying to set it when the existing value isn't already the same or default. It is too strict now by disallowing any value for CKA_ALWAYS_AUTHENTICATE if the current value isn't default.

I plan to create a new PR after this that stores the pin and touch policy in the slot struct from the attestation or metadata that gets called on first session open for a slot, so that getting them in C_GetAttributeVale becomes unnecessary. An attestation contains the policies as certificate extensions, and the origin is implicitly generated if you can create an attestation. This is important to avoid interacting with the PIV applet which could deauthenticate an always-auth key.

Best regards

**Comment by kevinjacobs** [comment]
> Hi, I have one final comment on the PR, and I think you might have meant this before and I missed that. For the CKA_ALWAYS_AUTHENTICATE I think to leave it out OR to pass a FALSE should mean the same thing, i.e. default PIN policy for that key. This is more in line with PKCS#11 in that specifying the default value for an attribute is exactly the same as not specifying it. Also, I think the test for CKA_ALWAYS_AUTHENTICATE should follow the pattern of the other two attributes, i.e. failing only if trying to set it when the existing value isn't already the same or default. It is too strict now by disallowing any value for CKA_ALWAYS_AUTHENTICATE if the current value isn't default.

That was a comment on the linked issue. I agree that we shouldn't change anything when the value is CK_FALSE. Fixed.


> I plan to create a new PR after this that stores the pin and touch policy in the slot struct from the attestation or metadata that gets called on first session open for a slot, so that getting them in C_GetAttributeVale becomes unnecessary. An attestation contains the policies as certificate extensions, and the origin is implicitly generated if you can create an attestation. This is important to avoid interacting with the PIV applet which could deauthenticate an always-auth key.

Interesting. That's a bit unexpected. Our library uses CKA_ALWAYS_AUTHENTICATE + TOUCH_ALWAYS. It probes the touch policy and returns to the application (which creates a GUI or CLI touch prompt, if appropriate). The Sign operation occurs after but calls login on its own, so it works fine. Sorry about that.

Thanks again for the reviews.

**Comment by qpernil** [comment]
As a final note I think there is a slight problem in that the code might call get_pr_metadata_attrs several times for a single C_GetAttributeValue call, and for multiple such calls as well, of course. So some caching might be in order. Also, if the YubiKey supports attestation (and the key is generated) you could get the information that way even if metadata is not supported. Both problems are addressed by the change I proposed above.

**Comment by qpernil** [comment]
Thanks a lot for your contribution, very nice work. I appreciate your responsiveness and not least the comprehensive tests, and this will get merged into the next release. We will start work on merging the outstanding PRs very soon, so I'd like to ask if you are going to create another PR for the import case as well, in the near future ?
Thx!

**Comment by kevinjacobs** [comment]
> ...so I'd like to ask if you are going to create another PR for the import case as well, in the near future ? Thx!

Yes - can't promise that I'll get started before the weekend, so look for something next week. I'll see about caching the get_metadata response there too.

Thanks again!

**Comment by qpernil** [comment]
Thx, that will be great. No need to cache, unless you want to use that in your own branch, as I will implement saving of these properties in the slot based on the initial attestation/metadata read that is already done when the first session is opened on a slot.

**Pull request merged**
