### PR TITLE
Fix FASC-N encoding

### PR DESCRIPTION
**Pull request by solidgoldbomb**
The encoding for the FASC-N field in the CHUID did not match Figure 7 in ["Technical Implementation Guidance: Smart Card Enabled Physical Access Control Systems Version 2.2"](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/TIG_SCEPACS_v2.2_0.pdf) which should be authoritative for this field.

The 5-bit encoding is easy to verify visually.  The first 4-bits should be the number (0-9) encoded in binary and then bit-flipped so that the lsb is first and msb is last.  The 5th bit should be an odd parity across the 4-bit number.  The new perl code matches the spec.

After correcting the fasc.pl tool, I regenerated the CHUID_TMPL in lib/util.c to make use of the corrected encoding.

Tested against a yubikey neo using ykman (reads CHUID) and piv-tool (reads GUID/serial only).

I've also verified that the fixed encoding produces a match with the only [online encoder](http://www.christhilges.com/fasc-n/index.php) I could find.  That's not much of a proof but it's all I could come up with for interop testing.

The perl code was touched recently in relation to #177, and the discussion included cautions from @mouse07410 about changing this at all but it's so clearly broken in its current state (e.g. '3' generates an entirely invalid BCD code point) that fixing it seems wise.

### CODE REVIEW

**Comment by solidgoldbomb** [comment]
Thanks for the info.  I don't have access to those applications but I understand that the CHUID field is used to uniquely identify individual persons employed by (or otherwise associated with) the US government.  Could you  help to clarify how best to remain compatible with these other tools?

Would it somehow be better/more compatible with those packages if the FASC-N field is malformed on the yubikey?  The encoding used by this tool seems to deliberately choose Agency Code 9999 which is reserved to mean a non-federal issuer.  Is that helpful or is that actively harmful?

**Comment by mouse07410** [comment]
> Could you help to clarify how best to remain compatible with these other tools?

By **not** looking like a token issued by a US Gov't agency, of course. Like, having `SS=9999`.

> Would it somehow be better/more compatible with those packages if the FASC-N field is malformed on the yubikey?

Don't know. Malformed - probably not. So turning what's supposed to be BCD into valid BCD is probably good. But the actual values must point at a non-federal issuer. 

> The encoding used by this tool seems to deliberately choose Agency Code 9999 which is reserved to mean a non-federal issuer. Is that helpful or is that actively harmful?

What do you think? If you are a federal issuer - you can generate a valid code, but in that case most likely you'd be using tools other than `yubico-piv-tool`. And if you are not a federal issuer - ask yourself if you have a reason to generate a value that falsifies a real agency, and what a likely consequence of presenting such a "forged" ID to an entity that can parse and verify that field would be.

**Comment by klali** [comment]
This looks sane to me, matching with something else (the referenced website) is good enough for me.

Thanks!

**Comment by solidgoldbomb** [comment]
Thanks for the review and for merging.  Companion fix for ykman has also been pushed.

**Comment by mouse07410** [comment]
> Companion fix for ykman has also been pushed

Funny, I can't seem to find that repo. Would you mind posting the pointer here?

**Comment by solidgoldbomb** [comment]
https://github.com/Yubico/yubikey-manager/pull/200

**Pull request merged**
