### PR TITLE
CMake: Honor standard variables

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Do not ignore the variables that control CMake's RPATH handling,
      such as `CMAKE_INSTALL_RPATH` (which is enabled by default anyway)
- [x] Honor the standard `CMAKE_INSTALL_*` variables for install directories.

Both of those changes came up when packaging v2.1.1 for Debian,
as the CMake-based build system was failing to obey any of the standard
configuration variables.

This change should be backwards compatible, in that the defaults should
stay the same, and users who previously set `YKPIV_*` still override any
other variables.

### CODE REVIEW

**Comment by nbraud** [comment]
6a91dcd got merged, then immediately reverted by 283e2e7c3af7138752f1df181bdce5fabd53ed1b.
Could you explain why / what happened?

**Comment by aveenismail** [comment]
Hi @nbraud 

It was necessary to specifically set the RPATH when building for MacOS, otherwise the library and the commandline tool weren't linking correctly. We didn't see that setting the RPATH made a difference when building for a Linux system, and that's why we left it there. 

Did you see a different behavior with Debian? Do you see a downside for doing it this way?

**Comment by nbraud** [comment]
> Did you see a different behavior with Debian? Do you see a downside for doing it this way?

Yes, this makes the build [non-reproducible], i.e. rebuilding the same source, with the same toolchain, will give different results depending on the build path.  Setting `CMAKE_BUILD_RPATH_USE_ORIGIN` or `CMAKE_BUILD_WITH_INSTALL_RPATH` might work to have builds that are both reproducible-by-default and work on macOS.

[non-reproducible]: https://reproducible-builds.org/docs/deterministic-build-systems/#cmake-notes

**Comment by aveenismail** [comment]
An update was committed to set INSTALL_RPATH only when building on MacOS. I hope this resolves the issue

**Pull request merged**
