### PR TITLE
Note about attestation cert problems in YubiKey 4.3

### PR DESCRIPTION
**Pull request by labanskoller**
Add a note to Using Attestation [1] about the certificate problems with
YubiKey 4.3.

[1] https://developers.yubico.com/yubico-piv-tool/Attestation.html

### CODE REVIEW

**Comment by labanskoller** [comment]
Note that I've not built the website.

**Comment by labanskoller** [comment]
Also my recently published blog post about the certificate problem: https://labanskoller.se/blog/2019/12/30/pki-is-hard-how-yubico-trusted-openssl-and-got-it-wrong/

**Comment by klali** [comment]
Attestation was never available for the Neo so to avoid confusion we should probably not mention it here. Apart from that lgtm.

**Comment by labanskoller** [comment]
> Attestation was never available for the Neo so to avoid confusion we should probably not mention it here.

Hmm. I don't have a Neo myself but I got that information from the following support article (my emphasis):
https://support.yubico.com/support/solutions/articles/15000013406-piv-attestation-verification-fails-with-openssl-1-1-0

> If you are attempting to verify a PIV attestation using the default attestation certificate loaded in the YubiKey 4 or **YubiKey NEO** and OpenSSL 1.1.0, the verification will fail. This is caused by an issue with the PIV Attestation Root Certificate. Starting with the YubiKey 5 series, an updated PIV Attestation Root Certificate is available which works with OpenSSL 1.1.0. To work around this issue with the **YubiKey NEO** or YubiKey 4 series devices, you can use the attached Python script and the steps below to verify the attestation certificate chain.

Are you suggesting that the above article is wrong or have I misunderstood anything? If that information is incorrect, will you have it updated or shall I initiate that via your support?

**Comment by klali** [comment]
Yes, that information is wrong, I'll try to get that updated internally.

**Comment by klali** [comment]
Actually there is a note about this at https://developers.yubico.com/PIV/Introduction/PIV_attestation.html (or at least linking to the KB), maybe it'd be better to make that clearer? or do you think this is better here?

**Comment by labanskoller** [comment]
Great! Yes, I know about the notice on that page. Feel free to improve that too, but the reason for this pull request is that the information is too far away from the `openssl verify` command that's not working on old YubiKeys and modern OpenSSL. In fact it took me over six months to realize that you had published the support article because I visited the "wrong" page once in a while and expected it to be updated with the information.

I'll update this PR with the correct information.

**Pull request merged**
