### PR TITLE
Handle removed objects during active object search

### PR DESCRIPTION
**Pull request by yota9**
Ensure that the session's object finding logic marks removed objects as
invalid and skips them during the search. This prevents the retrieval
and usage of objects that have been destroyed in an active session.
E.g. during removing key pairs cert + data objects got removed and the
CK_OBJECT_HANDLE returned by C_FindObjects() for one of them was
invalid.

### CODE REVIEW

**Comment by qpernil** [comment]
I think it is within spec to return invalid object handles if you destroy objects during an active search, see the pkcs#11 documentation for C_FindObjectsInit, which in my reading states that it is up to the implementation to decide if new or deleted objects will be found if objects are created or destroyed while a search operation is active. I would advice you to initiate another search after deleting the objects you want to delete, as you wouldn't know (in general) if the search results would reflect your changes or not.

**Comment by qpernil** [comment]
The way I see it if an application is using pkcs#11 it is often written to work with any pkcs#11 module, and as such could not count on that behaviour in general. The other factor is that in my opinion one should also add new objects to the active search if one wanted to implement a 'dynamic' kind of behaviour of active searches, and that is not possible with the current way the searches work, i.e. that we don't save the template but rather perform the search already in C_FindObjectInit and then save the results instead. Saving the template is more complicated as we can't depend on the template remaining valid after the call to C_FindObjectsInit returns, and thus we would have to make a deep copy of it. Without that we can't know if new objects should be added to an active search.

**Comment by yota9** [comment]
You're right with this one. But usually adding new while iterating old is not so common scenario, that is why I skipped this change :) Anyway, thank you for your answers, maybe at least it would help someone who will face similar problems :)

**Comment by qpernil** [comment]
Closing this PR now, thanks for your interest.

**Pull request closed without merging**
