### PR TITLE
Make libykcs11.so a module and configure p11-kit to see it

### PR DESCRIPTION
**Pull request by opoplawski**
This is a rebase of #176 that makes libykcs11.so a proper p11-kit module

### CODE REVIEW

**Comment by qpernil** [comment]
Just a query, not very familiar with p11-kit .. Wouldn't just a module configuration file suffice ? 
One would have to solve the different library suffix somehow of course.

**Comment by mouse07410** [comment]
Yes, adding a config file, like `~/.config/pkcs11/modules/ykcs11.module` is sufficient. Tested on MacOS and Linux.

**Comment by qpernil** [comment]
Could you elaborate what you mean when you say .so works ? We don't install a file with the .so suffix (in the current master)

**Comment by opoplawski** [comment]
The module config file is the main thing - it should be made into a .in file and use DYN_LIB_EXT for the extension I think.  Most pkcs11 modules do not use a soversion because they are dlopen()ed instead of linked - though I see from the travis failures that there is at least one think that links to it.  I still think you can drop the soversion because the interface is fixed.  I'll try to clean things up soon if I can find some time.

**Comment by opoplawski** [comment]
Looks like libtool uses the .so extension for plugins and this appears to work for MacOS.  There is a test that links with the plugin directly which isn't really the correct thing to do, but I guess is okay for a test.

**Comment by qpernil** [comment]
I would prefer to just add a module file and leave the rest unchanged. Any objections to that ?
Still need to figure out how to deal with the shared lib suffix in that case.

**Comment by opoplawski** [comment]
Well, do what you want, but I believe that this is a more proper way to make a pkcs11 module.

**Comment by aveenismail** [comment]
Hi @opoplawski 

I'm so sorry for coming in this late. As you can see, the building process have been changed from using automake to using cmake, which makes this pull request incompatible with the new version. We are, however, looking into adding support for p11-kit.

I'm so sorry that the build change has not been communicated more clearly earlier.

**Pull request closed without merging**
