### PR TITLE
Imporve ykpiv_connect failure user message

### PR DESCRIPTION
**Pull request by alonbl**
Provide a hint for user that PC/SC service may be down, as user should take
a specific action to resolve the issue.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

### CODE REVIEW

**Comment by qpernil** [comment]
Need to check how this works on different OS:es, I suspect the error code might differ..

**Comment by alonbl** [comment]
Hello @qpernil,
Can you please have another look?
All pcsc implementations have `SCARD_E_NO_SERVICE` and also in the remotely chance that it is not available the previous functionality will be provided and return value will be `YKPIV_PCSC_ERROR` as of now.
Thanks,

**Comment by qpernil** [comment]
I have cerated https://github.com/Yubico/yubico-piv-tool/pull/407 that maps PCSC errors everywhere, and includes your proposed new error code, which is printed as well now. I skipped your changes to the pkcs11 module as they were only debug output which is generated anyway. Let me know if this would solve your issue.

**Comment by alonbl** [comment]
Thanks!
It seems ok.
However, the missing bit is to understand what happens, you already have errors (not debug) for regular user to hint what's wrong, the error should be improved, I will note it in the other patch.

Superseded-By: #407

**Pull request closed without merging**
