### PR TITLE
T0 support

### PR DESCRIPTION
**Pull request by koh-osug**
I'm using the tool with a card only supporting T0. Support for this was missing.

### CODE REVIEW

**Comment by aveenismail** [comment]
Thank you for the patch @koh-osug. We are somewhat curious about why you need support for T0?

**Comment by kaoh** [comment]
I have a smart card only offering T=0 and installed a PIV applet on it.

**Comment by qpernil** [comment]
Just curious again - why use yubico-piv-tool in that case ?

**Comment by kaoh** [comment]
yubico-piv-tool is the only tool I know to manage the PIV token. If no T0 is supported it is becoming useless for my smart cards and I have to maintain a fork for my needs. What would be the alternative? Why is #329 breaking the T0 support?

**Comment by qpernil** [comment]
Sorry I wasn't clear - It has nothing to do with T0 support, but will reject non-yubico PIV applets, based on the support for our proprietary get-version instruction.

**Comment by qpernil** [comment]
Played around with the PCSC protocol tracking, have a look at 8d3eacf128748a238a1eabf55f81cdb14eb7cedc

**Comment by kaoh** [comment]
> Played around with the PCSC protocol tracking, have a look at [b9389db](https://github.com/Yubico/yubico-piv-tool/commit/b9389db250b6f28ef5e807e87c3e53d1eddd2d84)

Looks good, in case the state should be persisted.

**Comment by qpernil** [comment]
Had to change it a couple of times because it didn't compile on Windows. Force pushed.
I just thought this might be merged with your changes.

**Comment by kaoh** [comment]
> Sorry I wasn't clear - It has nothing to do with T0 support, but will reject non-yubico PIV applets, based on the support for our proprietary get-version instruction. This makes sense when trying to enumerate all YubiKeys without filtering on pcsc reader names, particularly to support NFC readers. This instruction has been there long enough it will work for all contemporary YubiKeys. But the change that rejects non-YubiKeys is built into ykpiv_connect in that PR, so it would affect anything based on libykpiv, not just ykcs11..

I haven't looked into the details and if it is really necessary to exclude tokens just following the PIV specification and not having the Yubico extension. Could the goals of the new feature also achieved with a fallback solution? In my case the applet is implementing the Yubico extensions and I might not be affected. But there is also the interesting [OpenFIPS](https://github.com/makinako/OpenFIPS201) implementation featuring a FIPS certification which is interesting in high security / federal environments which I assume the Yubico tokens are not offering. This implementation is not implementing the Yubico extensions

**Comment by kaoh** [comment]
> Had to change it a couple of times because it didn't compile on Windows. Force pushed. I just thought this might be merged with your changes.

Sure.

**Comment by qpernil** [comment]
What I wanted was a way to support NFC readers seamlessly in ykcs11, and we were checking the version already. So it was literally a one-liner to exclude non-YubiKey PIV applets, which was previously done by filtering on reader name. The change in yubico-piv-tool just follows from where I changed it, it wasn't really a desire to have it would mostly make sense there too.
Im curious what applet implements that extension.. Is it something you wrote yourself ? Anyway, I haven't tested the tool with a non-YubiKey, that was never intended to be supported. I'd be interested to know what else may have broken with that applet ?

**Comment by kaoh** [comment]
The other applet I'm using is the [PivApplet](https://github.com/arekinath/PivApplet). These two applets are the most advanced and functional applets I'm aware of. I know of some large companies in the US and federal institutions of the five eyes states which are also using the PIV standard, based on some of these applets or commercial solutions. I would assume they are also using for some administrative tasks the Yubico piv tools.

**Comment by qpernil** [comment]
OK, would you mind rebasing on top of the track-protocol branch ? I have to admit I was unaware of this use-case for yubico-piv-tool..

**Comment by kaoh** [comment]
> OK, would you mind rebasing on top of the track-protocol branch ? 

Yes, will do. 

> I have to admit I was unaware of this use-case for yubico-piv-tool..

Yes, sometimes it is interesting who is using open source silently.

**Comment by kaoh** [comment]
I tried to merge it. Somehow the rebasing showed conflicts.

**Comment by qpernil** [comment]
I wonder if the Le handling is correct in this code. As far as I can interpret 7816-3 it looks to me that Le in an APDU is not encoded in a TPDU. What is your take on that ?

**Comment by qpernil** [comment]
I've refactored things a bit in my branch track-protocol. I think it was incorrect that many functions were calling the _send_data function directly, when that function was really a _send_tpdu type function. So I refactored it to always use _ykpiv_transfer_data, through _ypkpiv_send_apdu for those functions that want to build up a (limited length) command apdu in the APDU struct and send it. The old _send_data is now called _send_tpdu. If you would be kind enough to test this I'd appreciate it. It doesn't currently handle the 6cXX status code, let me know if that is needed.

**Comment by kaoh** [comment]
> I wonder if the Le handling is correct in this code. As far as I can interpret 7816-3 it looks to me that Le in an APDU is not encoded in a TPDU. What is your take on that ? Have you been able to test that code path ?

The structure where I added the Le byte is the APDU structure. Without it a segmentation fault was raised later, I guess in the code also full case 4 APDUs are used including an Le byte.  For T1 the implementation does not have to care for this, I guess.

**Comment by kaoh** [comment]
> It doesn't currently handle the 6cXX status code, let me know if that is needed.

Not sure, if I just added it for completeness or if it failed without it because an Le was not accepted.

**Comment by qpernil** [comment]
Since the _send_data function directly calls SCardTransmit the APDU structure is really a tpdu at that stage. And the spec seems to say not to encode Le for a case 4 apdu in the tpdu. It's very confusing since the spec speaks of how Le _is_ encoded in the apdu. And for case 2 it is in fact encoded in the tpdu, in the same offset as Lc, so in our APDU struct it would be lc, with the only difference being that no data follows. So to me it looks more correct before the 091eb30436cd4dfbb79a587da208ceb66770181e commit.

**Comment by kaoh** [comment]
I now know that this was important for the 6C handling and [Case 2S.3 – Le not accepted, La indicated](http://cardwerk.com/iso-7816-4-annex-a-smart-card-standard/#AnnexA_2S_3), but you should be right, that here Lc falls together with Le, I don't know why I added an extra byte then. But when looking into this the 6C handling might be important for the Case 3 to be able to return data if the applet is enforcing that the send APDU must have the exact Le set.

**Comment by qpernil** [comment]
I've now made a PR from my track-protocol branch here https://github.com/Yubico/yubico-piv-tool/pull/340. If you have the inclination to test that code it would be appreciated.

**Comment by qpernil** [comment]
Closing this PR as it is adressed in #340

**Comment by qpernil** [comment]
If you have any issues with yubico-piv-tool with your smartcard I'd appreciate a heads-up so we can fix anything that makes sense. Thx!
/Per

**Comment by koh-osug** [comment]
Thanks a lot. Everything looks alright right, as long as the transport layer works, it should behave the same way like a Yubico token.

**Pull request closed without merging**
