### PR TITLE
Add 7816.3 T=0 support

### PR DESCRIPTION
**Pull request by qpernil**

### CODE REVIEW

**Comment by koh-osug** [comment]
By using this branch with a T=0 card this is working:

    yubico-piv-tool -astatus -r"Alcor Micro AU9560 00 00"

This fails (parts of it):

    yubico-piv-tool -r"Alcor Micro AU9560 00 00" -s9a -ibadssl.com-client.p12 -aimport-key -aimport-cert -v9999 -KPKCS12

The 6C handling seems to be in place, but I see a `SCardTransmit on card #0 failed, rc=80100008`?

~~~
> 00 a4 04 00 05 a0 00 00 03 08  (10)
< 61 73  (2)
The card indicates there is 115 bytes more data for us.
> 00 c0 00 00 73  (5)
< 61 71 4f 0b a0 00 00 03 08 00 00 10 00 01 00 79 0d 4f 0b a0 00 00 03 08 00 00 10 00 01 00 50 14 50 69 76 41 70 70 6c 65 74 20 76 30 2e 38 2e 32 2f 52 45 53 5f 50 26 68 74 74 70 73 3a 2f 2f 67 69 74 68 75 62 2e 63 6f 6d 2f 61 72 65 6b 69 6e 61 74 68 2f 50 69 76 41 70 70 6c 65 74 ac 14 80 01 03 80 01 06 80 01 07 80 01 11 80 01 f0 80 01 f1 06 00 90 00  (117)
Going to send 0 bytes in this go.
> 00 20 00 80 00  (5)
< 63 c5  (2)
Going to send 0 bytes in this go.
> 00 fd 00 00 00  (5)
< 6c 03  (2)
Going to send 0 bytes in this go.
> 00 fd 00 00 03  (5)
SCardTransmit on card #0 failed, rc=80100008
Failed to retrieve version: 'Error in PCSC call'
Going to send 0 bytes in this go.
> 00 f8 00 00 00  (5)
< 6c 04  (2)
Going to send 0 bytes in this go.
> 00 f8 00 00 04  (5)
SCardTransmit on card #0 failed, rc=80100008
Failed communicating with card: 'Error in PCSC call'
Failed to retrieve serial number: 'Error in PCSC call'
~~~

The install seems to succeeds part from this error.

**Comment by qpernil** [comment]
I wasn't resetting recv_len for the retry case, pushed a fix now. Please let me know if that helps.

**Comment by koh-osug** [comment]
Looks, I'm seeing now error in my test cases.

**Comment by qpernil** [comment]
I read that as no errors now. Could you confirm if you are satisfied with this branch instead of yours, so I can merge it ?
And many thanks for testing this !

**Comment by koh-osug** [comment]
Yes, it seems to work for all of my cases.

**Review by aveenismail — APPROVED** [review]

**Pull request merged**
