### PR TITLE
Add import/export of CHUID

### PR DESCRIPTION
**Pull request by ryanchapman**
Support for exporting and importing a CHUID object, signed or unsigned, as requested in #48  

Still need an external tool to sign a CHUID and create a CHUID based on input (FASC-N, GUID, expire, etc.)

### CODE REVIEW

**Comment by klali** [comment]
Hello,
I'm not certain on adding a custom file format and two more actions specific to chuid. I just pushed a branch (https://github.com/Yubico/yubico-piv-tool/tree/generic_objects) for doing generic object read/write. Right now it only does hex dump, but we could probably add more flexible data formats there (base64/binary?).
Thoughts?

**Comment by ryanchapman** [comment]
Hi Klas,

I like your method better, because lots of other objects are needed for FIPS 201 compliance which would lead to many more actions being added.

I tested read-object and write-object with the NIST Basic Card 'signed chuid' file they provide and it looks good.

# Set a random CHUID to get an initial state
```$ ./tool/yubico-piv-tool -a set-chuid
Successfully set new CHUID.
$ piv-tool -s "00:CB:3F:FF:05:5C:03:5F:C1:02:00"
Using reader with a card: Yubico Yubikey NEO CCID
Sending: 00 CB 3F FF 05 5C 03 5F C1 02 00
Received (SW1=0x90, SW2=0x00):
53 3B 30 19 D4 E7 39 DA 73 9C ED 39 CE 73 9D 83 S;0...9.s..9.s..
68 58 21 08 42 10 84 21 38 42 10 C3 F5 34 10 DF hX!.B..!8B...4..
0C 9E B0 16 5E BD 6D DC 86 A0 C7 D0 C4 8D 15 35 ....^.m........5
08 32 30 33 30 30 31 30 31 3E 00 FE 00          .20300101>...

# The NIST signed CHUID can be found in the zip file `http://csrc.nist.gov/groups/SNS/piv/documents/PIV-BasicCard-06262007.zip`

# Convert NIST CHUID signed file to hex-encoded
```
$ cat nist-signed-chuid | xxd -pu | tr -d '\n' > nist-signed-chuid-hexencoded
$ cat nist-signed-chuid-hexencoded
ee02f9053019d6501858210c2d3171b525a1685a08c92ade0a6186501843e2341031323334353637383930313233343536350832303039303832343d003e8205b8308205b406092a864886f70d010702a08205a5308205a1020103310b300906052b0e03021a0500300a06086086480165030601a08203713082036d30820255a00302010202022710300d06092a864886f70d01010505003032310b3009060355040613025553310d300b060355040a13044e495354311430120603550403130b5049562054657374204341301e170d3037303431393135323233335a170d3135303431393135323233335a303e310b3009060355040613025553310d300b060355040a13044e4953543120301e06035504031317504956205465737420436f6e74656e74205369676e657230820122300d06092a864886f70d01010105000382010f003082010a028201010097b6b124df0b637f1de58fa6e3ed1f9a40cc0108e87b63226da09db47c5fd1fea1c06ad8851a7609c35a6ed0a78e6d1843f0d0d9f2e005bd5c659c24ce79be32489cf5c83090d486350fe179842ee1af28eb0b968f68665085a75514a1c82302dc85e50d8b857ef1ecc760b1e2faac23c814f17ef408683b24d45791b442fce5b90dfb2277f4230499b459f806b8abe012736bc7dde4f328880a1252df6ee3581b72a8756cb1dbead8917f9cbdb1abd14cf524bd5e7932d89d9863137c21c933b7492130fe6052a7b5ea79b314986aa549472e1fbe4766eba67ca34d942c4716805301e7858a468c6eb7b0b050e8cb82691e6e3ed37016935b55239a23ed69770203010001a38180307e301f0603551d23041830168014ebda19d208428df4de258769c9bbab0cd3963001301d0603551d0e041604142645af29e87c9ad71a17b3dc79e2d2ff999e336e30170603551d200410300e300c060a6086480165030201030830130603551d25040c300a06086086480165030607300e0603551d0f0101ff040403020780300d06092a864886f70d010105050003820101007988cc1e4bea88a3176e4861a981d3e38a6993c900cb4372df023ecd66bf055861c851f9739db2d464dcf23f1ad38d55e76f78aa9c14457e6a8ca30d642fcd23c160ee35295cbd3ad0ae5113bfe44eeec0983b5f072c2e41c1f14689f4d136a9fe85c965a28c68d40d15b2ba2a64d437f5deeec4a6631c2fcefddb39b0b71777249c0d924d80eb24ffa4c16032dc943c5a4aa5631512ab711a57a9049aa11aa67f1550850439af3fe8a555ea7ae23a896ff99ec72e12f11b818816935e04456cf71f2d3b522eb2e531e9475fc7e59db3684d766535aea645e4ad780ff5eac0ea9acdb40161ba67f5aca1e68ae09d032a49d7fc322133296650b179d0a0d3eb913182020c3082020802010130383032310b3009060355040613025553310d300b060355040a13044e495354311430120603550403130b504956205465737420434102022710300906052b0e03021a0500a081aa301706092a864886f70d010903310a06086086480165030601301c06092a864886f70d010905310f170d3037303531373231303435305a302306092a864886f70d0109043116041459402585b8805a8b787a47f879778611ca16d09f304c060860864801650306053140303e310d300b060355040a13044e495354310b30090603550406130255533120301e06035504031317504956205465737420436f6e74656e74205369676e6572300d06092a864886f70d01010105000482010095970db361333d10ef2caa9b46e06855caccd274e2b26643b6baeeab14ceb2a295194b4f83c50d08aa80f085dd16e08e69170af4b6e658cceadd2d56de24b81af7e1c72224787e7f9fbd5e6d162fcbecc30e4da38aebafd3f5d3d93ace099ae8e92d0a0be4a4ead5bbc8191e1fb8f5e328921b03cb8490d3cfe125408a85847d89fe555f4217b09c42c12da016270add1170b12df093acd33a60f996f55d415e5cfeb464a6ae7605e0d9033e60a0895992b30c5fe0b7531b98655014a0acd82abd86c583077cf5576beb5395dc2b3a77292aa979221b7db0daf29a27c93d9ef90cdf8acce017f49afcdbd06b7b1ad708c4bebbf74c70b119a7514d8715bde369fe00```

# Write NIST CHUID signed file to Yubikey
```$ ./tool/yubico-piv-tool -a write-object --id 0x5fc102 -i nist-signed-chuid-hexencoded```

# Read CHUID off Yubikey and strip off newlines
```$ ./tool/yubico-piv-tool -a read-object --id 0x5fc102 -o out ; cat out | tr -d '\n' > out2```

# Check that what we wrote to the card is what we read back from the card
```$ shasum nist-signed-chuid-hexencoded out2
2df35fffcf97191f139b78b301bef5b58406416a  nist-signed-chuid-hexencoded
2df35fffcf97191f139b78b301bef5b58406416a  out2
```

# Double check using the APDU defined for retrieving the CHUID object
```$ piv-tool -s "00:CB:3F:FF:05:5C:03:5F:C1:02:00"
Using reader with a card: Yubico Yubikey NEO CCID
Sending: 00 CB 3F FF 05 5C 03 5F C1 02 00
Received (SW1=0x90, SW2=0x00):
53 82 05 FB EE 02 F9 05 30 19 D6 50 18 58 21 0C S.......0..P.X!.
2D 31 71 B5 25 A1 68 5A 08 C9 2A DE 0A 61 86 50 -1q.%.hZ..*..a.P
18 43 E2 34 10 31 32 33 34 35 36 37 38 39 30 31 .C.4.12345678901
32 33 34 35 36 35 08 32 30 30 39 30 38 32 34 3D 234565.20090824=
00 3E 82 05 B8 30 82 05 B4 06 09 2A 86 48 86 F7 .>...0.....*.H..
0D 01 07 02 A0 82 05 A5 30 82 05 A1 02 01 03 31 ........0......1
0B 30 09 06 05 2B 0E 03 02 1A 05 00 30 0A 06 08 .0...+......0...
60 86 48 01 65 03 06 01 A0 82 03 71 30 82 03 6D `.H.e......q0..m
30 82 02 55 A0 03 02 01 02 02 02 27 10 30 0D 06 0..U.......'.0..
09 2A 86 48 86 F7 0D 01 01 05 05 00 30 32 31 0B .*.H........021.
30 09 06 03 55 04 06 13 02 55 53 31 0D 30 0B 06 0...U....US1.0..
03 55 04 0A 13 04 4E 49 53 54 31 14 30 12 06 03 .U....NIST1.0...
55 04 03 13 0B 50 49 56 20 54 65 73 74 20 43 41 U....PIV Test CA
30 1E 17 0D 30 37 30 34 31 39 31 35 32 32 33 33 0...070419152233
5A 17 0D 31 35 30 34 31 39 31 35 32 32 33 33 5A Z..150419152233Z
30 3E 31 0B 30 09 06 03 55 04 06 13 02 55 53 31 0>1.0...U....US1
0D 30 0B 06 03 55 04 0A 13 04 4E 49 53 54 31 20 .0...U....NIST1
30 1E 06 03 55 04 03 13 17 50 49 56 20 54 65 73 0...U....PIV Tes
74 20 43 6F 6E 74 65 6E 74 20 53 69 67 6E 65 72 t Content Signer
30 82 01 22 30 0D 06 09 2A 86 48 86 F7 0D 01 01 0.."0...*.H.....
01 05 00 03 82 01 0F 00 30 82 01 0A 02 82 01 01 ........0.......
00 97 B6 B1 24 DF 0B 63 7F 1D E5 8F A6 E3 ED 1F ....$..c........
9A 40 CC 01 08 E8 7B 63 22 6D A0 9D B4 7C 5F D1 .@....{c"m...|_.
FE A1 C0 6A D8 85 1A 76 09 C3 5A 6E D0 A7 8E 6D ...j...v..Zn...m
18 43 F0 D0 D9 F2 E0 05 BD 5C 65 9C 24 CE 79 BE .C.......\e.$.y.
32 48 9C F5 C8 30 90 D4 86 35 0F E1 79 84 2E E1 2H...0...5..y...
AF 28 EB 0B 96 8F 68 66 50 85 A7 55 14 A1 C8 23 .(....hfP..U...#
02 DC 85 E5 0D 8B 85 7E F1 EC C7 60 B1 E2 FA AC .......~...`....
23 C8 14 F1 7E F4 08 68 3B 24 D4 57 91 B4 42 FC #...~..h;$.W..B.
E5 B9 0D FB 22 77 F4 23 04 99 B4 59 F8 06 B8 AB ...."w.#...Y....
E0 12 73 6B C7 DD E4 F3 28 88 0A 12 52 DF 6E E3 ..sk....(...R.n.
58 1B 72 A8 75 6C B1 DB EA D8 91 7F 9C BD B1 AB X.r.ul..........
D1 4C F5 24 BD 5E 79 32 D8 9D 98 63 13 7C 21 C9 .L.$.^y2...c.|!.
33 B7 49 21 30 FE 60 52 A7 B5 EA 79 B3 14 98 6A 3.I!0.`R...y...j
A5 49 47 2E 1F BE 47 66 EB A6 7C A3 4D 94 2C 47 .IG...Gf..|.M.,G
16 80 53 01 E7 85 8A 46 8C 6E B7 B0 B0 50 E8 CB ..S....F.n...P..
82 69 1E 6E 3E D3 70 16 93 5B 55 23 9A 23 ED 69 .i.n>.p..[U#.#.i
77 02 03 01 00 01 A3 81 80 30 7E 30 1F 06 03 55 w........0~0...U
1D 23 04 18 30 16 80 14 EB DA 19 D2 08 42 8D F4 .#..0........B..
DE 25 87 69 C9 BB AB 0C D3 96 30 01 30 1D 06 03 .%.i......0.0...
55 1D 0E 04 16 04 14 26 45 AF 29 E8 7C 9A D7 1A U......&E.).|...
17 B3 DC 79 E2 D2 FF 99 9E 33 6E 30 17 06 03 55 ...y.....3n0...U
1D 20 04 10 30 0E 30 0C 06 0A 60 86 48 01 65 03 . ..0.0...`.H.e.
02 01 03 08 30 13 06 03 55 1D 25 04 0C 30 0A 06 ....0...U.%..0..
08 60 86 48 01 65 03 06 07 30 0E 06 03 55 1D 0F .`.H.e...0...U..
01 01 FF 04 04 03 02 07 80 30 0D 06 09 2A 86 48 .........0...*.H
86 F7 0D 01 01 05 05 00 03 82 01 01 00 79 88 CC .............y..
1E 4B EA 88 A3 17 6E 48 61 A9 81 D3 E3 8A 69 93 .K....nHa.....i.
C9 00 CB 43 72 DF 02 3E CD 66 BF 05 58 61 C8 51 ...Cr..>.f..Xa.Q
F9 73 9D B2 D4 64 DC F2 3F 1A D3 8D 55 E7 6F 78 .s...d..?...U.ox
AA 9C 14 45 7E 6A 8C A3 0D 64 2F CD 23 C1 60 EE ...E~j...d/.#.`.
35 29 5C BD 3A D0 AE 51 13 BF E4 4E EE C0 98 3B 5)\.:..Q...N...;
5F 07 2C 2E 41 C1 F1 46 89 F4 D1 36 A9 FE 85 C9 _.,.A..F...6....
65 A2 8C 68 D4 0D 15 B2 BA 2A 64 D4 37 F5 DE EE e..h.....*d.7...
C4 A6 63 1C 2F CE FD DB 39 B0 B7 17 77 24 9C 0D ..c./...9...w$..
92 4D 80 EB 24 FF A4 C1 60 32 DC 94 3C 5A 4A A5 .M..$...`2..<ZJ.
63 15 12 AB 71 1A 57 A9 04 9A A1 1A A6 7F 15 50 c...q.W........P
85 04 39 AF 3F E8 A5 55 EA 7A E2 3A 89 6F F9 9E ..9.?..U.z.:.o..
C7 2E 12 F1 1B 81 88 16 93 5E 04 45 6C F7 1F 2D .........^.El..-
3B 52 2E B2 E5 31 E9 47 5F C7 E5 9D B3 68 4D 76 ;R...1.G_....hMv
65 35 AE A6 45 E4 AD 78 0F F5 EA C0 EA 9A CD B4 e5..E..x........
01 61 BA 67 F5 AC A1 E6 8A E0 9D 03 2A 49 D7 FC .a.g........*I..
32 21 33 29 66 50 B1 79 D0 A0 D3 EB 91 31 82 02 2!3)fP.y.....1..
0C 30 82 02 08 02 01 01 30 38 30 32 31 0B 30 09 .0......08021.0.
06 03 55 04 06 13 02 55 53 31 0D 30 0B 06 03 55 ..U....US1.0...U
04 0A 13 04 4E 49 53 54 31 14 30 12 06 03 55 04 ....NIST1.0...U.
03 13 0B 50 49 56 20 54 65 73 74 20 43 41 02 02 ...PIV Test CA..
27 10 30 09 06 05 2B 0E 03 02 1A 05 00 A0 81 AA '.0...+.........
30 17 06 09 2A 86 48 86 F7 0D 01 09 03 31 0A 06 0...*.H......1..
08 60 86 48 01 65 03 06 01 30 1C 06 09 2A 86 48 .`.H.e...0...*.H
86 F7 0D 01 09 05 31 0F 17 0D 30 37 30 35 31 37 ......1...070517
32 31 30 34 35 30 5A 30 23 06 09 2A 86 48 86 F7 210450Z0#..*.H..
0D 01 09 04 31 16 04 14 59 40 25 85 B8 80 5A 8B ....1...Y@%...Z.
78 7A 47 F8 79 77 86 11 CA 16 D0 9F 30 4C 06 08 xzG.yw......0L..
60 86 48 01 65 03 06 05 31 40 30 3E 31 0D 30 0B `.H.e...1@0>1.0.
06 03 55 04 0A 13 04 4E 49 53 54 31 0B 30 09 06 ..U....NIST1.0..
03 55 04 06 13 02 55 53 31 20 30 1E 06 03 55 04 .U....US1 0...U.
03 13 17 50 49 56 20 54 65 73 74 20 43 6F 6E 74 ...PIV Test Cont
65 6E 74 20 53 69 67 6E 65 72 30 0D 06 09 2A 86 ent Signer0...*.
48 86 F7 0D 01 01 01 05 00 04 82 01 00 95 97 0D H...............
B3 61 33 3D 10 EF 2C AA 9B 46 E0 68 55 CA CC D2 .a3=..,..F.hU...
74 E2 B2 66 43 B6 BA EE AB 14 CE B2 A2 95 19 4B t..fC..........K
4F 83 C5 0D 08 AA 80 F0 85 DD 16 E0 8E 69 17 0A O............i..
F4 B6 E6 58 CC EA DD 2D 56 DE 24 B8 1A F7 E1 C7 ...X...-V.$.....
22 24 78 7E 7F 9F BD 5E 6D 16 2F CB EC C3 0E 4D "$x~...^m./....M
A3 8A EB AF D3 F5 D3 D9 3A CE 09 9A E8 E9 2D 0A ........:.....-.
0B E4 A4 EA D5 BB C8 19 1E 1F B8 F5 E3 28 92 1B .............(..
03 CB 84 90 D3 CF E1 25 40 8A 85 84 7D 89 FE 55 .......%@...}..U
5F 42 17 B0 9C 42 C1 2D A0 16 27 0A DD 11 70 B1 _B...B.-..'...p.
2D F0 93 AC D3 3A 60 F9 96 F5 5D 41 5E 5C FE B4 -....:`...]A^\..
64 A6 AE 76 05 E0 D9 03 3E 60 A0 89 59 92 B3 0C d..v....>`..Y...
5F E0 B7 53 1B 98 65 50 14 A0 AC D8 2A BD 86 C5 _..S..eP....*...
83 07 7C F5 57 6B EB 53 95 DC 2B 3A 77 29 2A A9 ..|.Wk.S..+:w)*.
79 22 1B 7D B0 DA F2 9A 27 C9 3D 9E F9 0C DF 8A y".}....'.=.....
CC E0 17 F4 9A FC DB D0 6B 7B 1A D7 08 C4 BE BB ........k{......
F7 4C 70 B1 19 A7 51 4D 87 15 BD E3 69 FE 00    .Lp...QM....i..
$```

**Comment by ryanchapman** [comment]
Closing this PR since Klas provided a better solution.

**Comment by mouse07410** [comment]
@klali yes, if you add the ability to dump base64 and raw/binary - I'd say it would be just perfect. And if you allow reading in all of these three formats (hex, base64, binary) - it would be beyond perfect. :-)

**Pull request closed without merging**
